# Negotiation Agents Configuration

[server]
host = "127.0.0.1"
port = 8000
workers = 4
max_connections = 1000

[database]
url = "sqlite://negotiation.db"
max_connections = 10
min_connections = 1
acquire_timeout_seconds = 30

[discovery]
endpoint = "http://localhost:8000"
cache_ttl_seconds = 300
max_cache_size = 1000

[settlement]
# stripe_secret_key = "sk_test_your_stripe_secret_key"
# solana_rpc_url = "https://api.mainnet-beta.solana.com"
# escrow_service_url = "http://localhost:8003"
# webhook_secret = "whsec_your_webhook_secret"

[trust]
# jwt_secret = "your-jwt-secret-key-here"
min_reputation_threshold = 50
reputation_decay_rate = 0.01
cache_ttl_seconds = 1800

[llm]
model = "gpt-3.5-turbo"
# api_key = "your-openai-api-key"
# api_base = "https://api.openai.com/v1"
max_tokens = 1000
temperature = 0.7
timeout_seconds = 30

[logging]
level = "info"
format = "json"
# file = "negotiation-agents.log"